name: inception

services:

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    env_file:
      - ./.env
    volumes:
      - ${DATA_PATH}/wordpress:/var/www/html
    networks:
      - inception_network
    restart: unless-stopped

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - ${DATA_PATH}/wordpress:/var/www/html
    networks:
      - inception_network
    env_file:
      - ./.env
    environment:
      BONUS_SETUP: ${BONUS_SETUP:-false}
    restart: unless-stopped

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    container_name: mariadb
    volumes:
      - ${DATA_PATH}/mariadb:/var/lib/mysql
    networks:
      - inception_network
    env_file:
      - ./.env
    restart: unless-stopped

  redis:
    build:
      context: ./bonus/redis
      dockerfile: Dockerfile
    image: redis_bonus
    container_name: redis
    profiles: [bonus]
    networks:
      - inception_network
    restart: unless-stopped

  ftp:
    build:
      context: ./bonus/ftp
      dockerfile: Dockerfile
    image: ftp
    container_name: ftp
    profiles: [bonus]
    volumes:
      - ${DATA_PATH}/wordpress:/var/www/html
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    env_file:
      - ./.env
    networks:
      - inception_network
    restart: unless-stopped

  adminer:
    build:
      context: ./bonus/adminer
      dockerfile: Dockerfile
    image: adminer
    container_name: adminer
    profiles: [bonus]
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    networks:
      - inception_network
    restart: unless-stopped

  static:
    build:
      context: ./bonus
      dockerfile: static/Dockerfile
    image: static
    container_name: static
    profiles: [bonus]
    ports:
      - "8888:8888"
    networks:
      - inception_network
    restart: unless-stopped

networks:
  inception_network:
    name: inception_network
    driver: bridge

